---
image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"

build-master:
  stage: build
  script:
    - docker build -t "$DOCKER_HUB_IMAGE:latest" .
    - docker push "$DOCKER_HUB_IMAGE:latest"
  only:
    - master

build-release:
  stage: build
  script:
    - docker build -t "$DOCKER_HUB_IMAGE:$( basename "$CI_COMMIT_BRANCH" )" .
    - docker push "$DOCKER_HUB_IMAGE:$( basename "$CI_COMMIT_BRANCH" )"
  only:
    - /^releases\/.*/
